// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydbuwwjdugmviwoilfws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkYnV3d2pkdWdtdml3b2lsZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDIzODMsImV4cCI6MjA1ODA3ODM4M30.vXOTc17BXFhcSn2_u5bY8rue2m41wxSFaW_G_MSBIa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);